name: flutter_wasmer
description: A Dart Wasmer Example.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^0.1.3
  cupertino_icons: ^0.1.2
  meta: ^1.1.8
  path_provider: ^1.6.1
  path_provider_macos: ^0.0.4
  path: ^1.6.4
  wasm_interop: ^1.0.0-dev.1.0

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.5.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - target/debug/
    - src/add.wasm
